version: 2
updates:
  # github actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

  # auth0 terraform monorepo
  - package-ecosystem: "terraform"
    directory: "/auth0/duo/aws/terraform"
    schedule:
      interval: "monthly"
  - package-ecosystem: "terraform"
    directory: "/auth0/duo/azure/terraform"
    schedule:
      interval: "monthly"
  - package-ecosystem: "terraform"
    directory: "/auth0/duo/gcp/terraform"
    schedule:
      interval: "monthly"

  # aws terraform monorepo
  - package-ecosystem: "terraform"
    directory: "/okta/duo/aws/terraform"
    schedule:
      interval: "monthly"
  - package-ecosystem: "terraform"
    directory: "/okta/duo/azure/terraform"
    schedule:
      interval: "monthly"
  - package-ecosystem: "terraform"
    directory: "/okta/duo/gcp/terraform"
    schedule:
      interval: "monthly"

  # npm terraform monorepo
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 20
  - package-ecosystem: "npm"
    directory: "/auth0/common"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 20
  - package-ecosystem: "npm"
    directory: "/auth0/duo/aws"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 20
  - package-ecosystem: "npm"
    directory: "/auth0/duo/azure"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 20
  - package-ecosystem: "npm"
    directory: "/auth0/duo/gcp"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 20
  - package-ecosystem: "npm"
    directory: "/common/cloud/aws"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 20
  - package-ecosystem: "npm"
    directory: "/common/cloud/azure"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 20
  - package-ecosystem: "npm"
    directory: "/common/cloud/gcp"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 20
  - package-ecosystem: "npm"
    directory: "/common/cloud/core"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 20
  - package-ecosystem: "npm"
    directory: "/common/cloud/mfa/duo"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 20
  - package-ecosystem: "npm"
    directory: "/okta/common"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 20
  - package-ecosystem: "npm"
    directory: "/okta/duo/aws"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 20
  - package-ecosystem: "npm"
    directory: "/okta/duo/azure"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 20
  - package-ecosystem: "npm"
    directory: "/okta/duo/gcp"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 20
