name: Audit

# Audit runs once a day (at noon UTC) and on master merges
on:
  repository_dispatch:
    types: manualTriggerAudit
  schedule:
    - cron:  '0 12 * * *'
  push:
    branches:
      - master

jobs:

  audit:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v1
      - name: 'Install Node.js'
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: 'Run Audit'
        run: |
          yarn install --frozen-lockfile
          yarn run improved-yarn-audit --exclude 1523 --ignore-dev-deps
