name: Build

# Build runs on master merges and pull request changes
on:
  repository_dispatch:
    types: manualTriggerBuild
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  build:
    name: 'Build and Test'
    runs-on: ubuntu-latest
    steps:
      - name: 'Testing new env variables'
        run: |
          echo "VERSION=\"`date '+%Y%m%d'`-`echo ${{github.sha}} | head -c 8`\"" >> $GITHUB_ENV
      - name: 'continue testing'
        run: |
          echo "ODED TESTING ${{ env.VERSION }}"
