name: Build

# Build runs on master merges and pull request changes
on:
  repository_dispatch:
    types: manualTriggerBuild
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  build:
    name: 'Build and Test'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2.3.4
      - name: 'Install Node.js'
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 12.x
      - name: 'Install Dependencies'
        run: |
          yarn install
      - name: 'Build and Test'
        run: |
          yarn lint
          yarn test
          yarn zip
          yarn build:docker
      - name: 'Verify Docker'
        run: |
          docker images
          docker run -i okta-duo-aws --help
